version: "3"

services:
  mongo:
    container_name: mongo_tg_bot
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-29017}:${MONGODB_PORT:-29017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    networks:
      - chatgpt_bot
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
        - chatgpt_bot


networks:
  chatgpt_bot:
    driver: bridge